INSERT INTO rasp2.order_exit_goods_rn_history
(
    date_id 
    ,batch_id 
    ,order_id
    ,order_doc_date 
    ,order_doc_num 
    ,order_guid_uid 
    ,unit_id
    ,unit_guid_uid 
    ,unit_name
    ,city_id
    ,city_guid_uid
    ,city_name
    ,order_contract_deliever_date
    ,parent_order_id
    ,parent_order_doc_date
    ,parent_order_doc_num 
    ,parent_order_guid_uid 
    ,client_id
    ,client_name
    ,client_guid_uid   
    ,order_phone 
    ,employee_id 
    ,employee_name
    ,employee_guid_uid    
    ,order_is_individual 
    ,order_is_kitchen
    ,order_mipik_collection_id
    ,order_mipik_collection_name
    ,order_mipik_collection_guid_uid   
    ,order_mipik_assortiment_group_id 
    ,order_mipik_assortiment_group_name
    ,order_mipik_assortiment_group_guid_uid   
    ,order_mipik_customization_type_id 
    ,order_mipik_customization_type_name
    ,order_mipik_customization_type_guid_uid    
    ,nomenclature_id
    ,nomenclature_guid_uid 
    ,nomenclature_name
    ,nomenclature_property_id 
    ,nomenclature_property_guid_uid 
    ,nomenclature_property_name
    ,art_id
    ,type_id 
    ,type_name 
    ,order_count 
    ,total_sum
    ,avg_price
    ,correct_order_count 
    ,correct_total_sum
    ,sale_order_count 
    ,sale_total_sum
)
SELECT
    date_id
    ,batch_id
    ,order_id 
    ,order_doc_date 
    ,order_doc_num 
    ,toUUIDOrZero(order_guid_str)
    ,unit_id
    ,toUUIDOrZero(unit_guid_str)
    ,unit_name
    ,city_id
    ,toUUIDOrZero(city_guid_str) 
    ,city_name
    ,order_contract_deliever_date
    ,parent_order_id
    ,parent_order_doc_date 
    ,parent_order_doc_num 
    ,toUUIDOrZero(parent_order_guid_str)
    ,client_id
    ,client_name 
    ,toUUIDOrZero(client_guid_str) 
    ,order_phone
    ,employee_id 
    ,employee_name 
    ,toUUIDOrZero(employee_guid_str)
    ,order_is_individual 
    ,order_is_kitchen
    ,order_mipik_collection_id 
    ,order_mipik_collection_name 
    ,toUUIDOrZero(order_mipik_collection_guid_str) 
    ,order_mipik_assortiment_group_id 
    ,order_mipik_assortiment_group_name 
    ,toUUIDOrZero(order_mipik_assortiment_group_guid_str)
    ,order_mipik_customization_type_id
    ,order_mipik_customization_type_name 
    ,toUUIDOrZero(order_mipik_customization_type_guid_str)
    ,nomenclature_id
    ,toUUIDOrZero(nomenclature_guid_str)
    ,nomenclature_name
    ,nomenclature_property_id 
    ,toUUIDOrZero(nomenclature_property_guid_str)
    ,nomenclature_property_name
    ,art_id
    ,type_id 
    ,type_name 
    ,order_count 
    ,total_sum
    ,avg_price 
    ,correct_order_count 
    ,correct_total_sum
    ,sale_order_count 
    ,sale_total_sum
FROM 
	from_mssql.vw_order_exit_goods_rn_yesterday
WHERE 
	date_id NOT IN (SELECT DISTINCT date_id FROM rasp2.order_exit_goods_rn_history)