-- mg, 2025-08-08
-- Заполнение таблицы [mg2].[monitoring_refresh_bi_report] - мониторинг автоматического обновления отчетов в Power BI Report Server 
INSERT INTO [mg2].[monitoring_refresh_bi_report](
	[ReportName] 
	,[ReportPath] 
    ,[ReportCreationUserName] 
    ,[ReportCreationDate] 
    ,[ReportModifiedUserName] 
    ,[ReportModifiedDate] 
    ,[ScheduleStartDate] 
    ,[ScheduleEndDate] 
    ,[ScheduleMinutesInterval] 
    ,[ScheduleDaysInterval] 
    ,[ScheduleWeeksInterval] 
    ,[ScheduleDaysOfWeek] 
    ,[ScheduleDaysOfMonth] 
    ,[ScheduleMonth] 
    ,[ScheduleMonthlyWeek] 
    ,[ScheduleLastRunTime] 
    ,[ScheduleCreationUserName] 
    ,[ScheduleModifiedDate] 
    ,[LastStatusSubscriptions] 
    ,[LastRunTimeSubscriptions] 
)
SELECT 
    rep.[Name] 				
    ,rep.[Path]				
    ,us_cr.[UserName] 		
    ,rep.[CreationDate] 	
    ,us_md.[UserName] 		
    ,rep.[ModifiedDate] 	
    ,sch.[StartDate] 		 
    ,sch.[EndDate]			
    ,sch.[MinutesInterval] 	
    ,sch.[DaysInterval] 	
    ,sch.[WeeksInterval] 	
    ,sch.[DaysOfWeek] 		
    ,sch.[DaysOfMonth] 		
    ,sch.[Month]			
    ,sch.[MonthlyWeek]		
    ,sch.[LastRunTime] 		
    ,us_sch.[UserName] 		
    ,sub.[ModifiedDate] 	
    ,sub.[LastStatus] 		
    ,sub.[LastRunTime] 		
FROM 
	[ReportServerMain].[dbo].[Subscriptions] 			AS sub
	LEFT JOIN [ReportServerMain].[dbo].[ReportSchedule] AS rs ON sub.[SubscriptionID] = rs.[SubscriptionID]
	LEFT JOIN [ReportServerMain].[dbo].[Catalog] 		AS rep ON rs.[ReportID] = rep.[ItemID]
	LEFT JOIN [ReportServerMain].[dbo].[Schedule] 		AS sch ON rs.[ScheduleID] = sch.[ScheduleID]	
	LEFT JOIN [ReportServerMain].[dbo].[Users] 			AS us_cr ON rep.[CreatedByID] = us_cr.[UserID]
	LEFT JOIN [ReportServerMain].[dbo].[Users] 			AS us_md ON rep.[ModifiedByID] = us_md.[UserID]
	LEFT JOIN [ReportServerMain].[dbo].[Users] 			AS us_sch ON sch.[CreatedById] = us_sch.[UserID]
